### ISSUE TITLE
Links along with text

### ISSUE THREAD

**Issue by kinalmehta** [jskherman/imprecv#25]
Ability to add links in any text location (eg. job highlights, projects description, etc)

I tried adding using `#link` function but it didn't work.

**Comment by jskherman** [comment]
Can you send an example snippet? For me, it seems to work with `v1.0.1` by making sure the strings in the YAML file is properly enclosed in `""` quotation marks and properly escaping the quotation marks in the `link()` function. This is because `#` starts a comment in YAML. For example:

```yaml
# ...
projects:
  - name: "Job Tailor"
    # ...other fields here
    highlights:
      - "Developed an #link(\"https://openrouter.ai\")[AI-powered] résumé editor app to create tailored résumés from users' CVs based on specific job descriptions."
# ...
```

**Comment by kinalmehta** [comment]
Thanks for clarifying. It works with the method you mentioned but only in `highlights`. However i'm trying to add link in the work/positions/position and it doesn't seem to be working. Example below
```yaml
work:
  - organization: IIIT Hyderabad
    url: # https://www.iiit.ac.in/
    location: Hyderabad, India
    positions:
      - position: "Graduate Research Assistant - #link(\"https://faculty.iiit.ac.in/~pawan.kumar/myhomepage/\")[Prof. Pawan Kumar]"
```
